### ISSUE TITLE
CISC troubles

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#798]
While trying out cisc, some troubles arose:
- [x] sometimes the actions fail with `websocket: close 4003: unexpected EOF` - mainly the voting
- [x] `cisc config vote` doesn't show the value of the new key
- [x] `cisc kv` should be more automatic and call `cisc config update` and `cisc config vote`
- [x] `cisc follow` should not overwrite `.ssh/authorized_keys` by default, but only if there are keys available

**Comment by ineiti** [comment]
Done
